name: booking_hotel
description: "A Flutter project, with clean architecture and BLoC as state management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  go_router: ^14.6.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  intl: ^0.19.0
  easy_localization: ^3.0.7
  flutter_rating_stars: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dev: ^1.0.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  flutter_gen_runner: ^5.8.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  network_image_mock: ^2.1.1

  mocktail: ^1.0.4
  bloc_test: ^9.0.0


flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
